export default {
  login: "IosifDobos",
  id: 22156333,
  node_id: "MDQ6VXNlcjIyMTU2MzMz",
  avatar_url: "https://avatars3.githubusercontent.com/u/22156333?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/IosifDobos",
  html_url: "https://github.com/IosifDobos",
  followers_url: "https://api.github.com/users/IosifDobos/followers",
  following_url: "https://api.github.com/users/IosifDobos/following{/other_user}",
  gists_url: "https://api.github.com/users/IosifDobos/gists{/gist_id}",
  starred_url: "https://api.github.com/users/IosifDobos/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/IosifDobos/subscriptions",
  organizations_url: "https://api.github.com/users/IosifDobos/orgs",
  repos_url: "https://api.github.com/users/IosifDobos/repos",
  events_url: "https://api.github.com/users/IosifDobos/events{/privacy}",
  received_events_url: "https://api.github.com/users/IosifDobos/received_events",
  type: "User",
  site_admin: false,
  name: "Iosif Dobos",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 24,
  public_gists: 0,
  followers: 6,
  following: 8,
  created_at: "2016-09-12T18:39:09Z",
  updated_at: "2020-10-22T20:24:10Z"
}
